### ISSUE TITLE
How working with docker volumes? Got errors volume does not exists...

### ISSUE THREAD

**Issue by ClaudioBsh** [pascaliske/docker-autorestic#74]
Many thanks for this nice software package you created!!

I currently test it with docker volumes, but get it not running as expected.

This is my ./config,yml:

version: 2
backends:
  my-to-backend:
    type: local
    path: /var/lib/autorestic/backends/my-to-backend
locations:
  my-from-location:
    from:
    - /var/lib/autorestic/locations/my-from-location
    to:
    - my-to-backend
  my-from-volumes:
    from:
    - pgdata
    type: volume
    to:
    - my-to-backend

This is the command i run:
docker run --rm -v ./config.yml:/etc/autorestic/config.yml -v ./cache:/etc/autorestic/cache -v ./backends/my-to-backend:/var/lib/autorestic/backends/my-to-backend pascaliske/autorestic:latest backup --location my-from-volumes

This is what i get:
Using config:    /etc/autorestic/config.yml
Using lock:      /etc/autorestic/.autorestic.lock.yml
    Backing up location "my-from-volumes"
Backend: my-to-backend
volume "pgdata" does not exist
Error: 1 errors were found

But docker tells me, there is such a volume:
docker volume ls
DRIVER    VOLUME NAME
local     pgdata

So i am wondering what is wrong?

**Comment by pascaliske** [comment]
Hi @ClaudioBsh,

Unfortunately this is expected - autorestic itself supports specifying docker volumes directly but this is not the case with it wrapped inside a docker image because the autorestic tool as no access to the hosts Docker daemon to back up the volume.

A possible workaround for this would be to mount the volume to the autorestic container (`-v pgdata:/var/lib/autorestic/locations/pgdata`) in your `docker run`-command and then specify it as a regular location:

```yaml
locations:
  my-from-volumes:
    from:
      - /var/lib/autorestic/locations/pgdata
    to:
      - my-to-backend
```

Hope this helps!

BR, Pascal
